### PR TITLE
Fix python releases

### LINKED ISSUE #145: Deltalake 0.4.3 (and 0.4.2) breaks our CI
Hi Again :)

We tried to upgrade our base code with deltalake 0.4.3 (also with 0.4.2) but we got an error during our CI process (when launching unit tests).

The error is 
`dags/utils/delta_lake_utils.py:4: in <module>
    from deltalake import DeltaTable, Schema
../../../virtualenv/python3.7.1/lib/python3.7/site-packages/deltalake/__init__.py:1: in <module>
    from .deltalake import RawDeltaTable, rust_core_version
E   ImportError: /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/deltalake/deltalake.abi3.so: undefined symbol: renameat2
 `

Everything is working well with deltalake 0.4.1 do you have any idea about this issue ?

### PR DESCRIPTION
**Pull request by houqp**
# Description

Avoid linking to renameat2 glibc symbol for old glibc versions. This should unblock python release. Delta write is not supported in python at the moment, so this should have no impact to python users.

Will add workarounds for old glibc and linux kernel in a separate follow up PR.

# Related Issue(s)

close #145 and #146.

### CODE REVIEW

**Comment by houqp** [comment]
also cc @mosyp @xianwill

File: rust/build.rs [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+        use regex::Regex;
+        use std::process::Command;
+
+        let output = Command::new("ldd")
+            .args(&["--version"])
+            .output()
+            .expect("failed to execute ldd");
+        let output_str = std::str::from_utf8(&output.stdout).unwrap();
+
+        let version_reg = Regex::new(r#"ldd \(.+\) ([0-9]+\.[0-9]+)"#).unwrap();
```
Comment (fvaleye) [inline rust/build.rs:14]: Maybe you can add a unit-test for extracting the regex with an example of the glibc version?

Comment (houqp) [reply rust/build.rs:14]: build.rs doesn't support unit test, let me pull those code into its own crate.

Comment (houqp) [reply rust/build.rs]: @fvaleye moved that to a different crate and added tests.

**Review by fvaleye — APPROVED** [review]
Perfect 👍
