### PR TITLE
fix: avoid writing statistics for binary columns to fix JSON error

### LINKED ISSUE #1493: Json error: Binary is not supported by JSON when writing checkpoint files
# Environment

**Delta-rs version**: Latest (master)

**Environment**: 
- **Cloud provider**: AWS
- **OS**: OSX, docker debian
- **Other**:

***
# Bug

**What happened**:

When writing checkpoints for a table with binary columns via:

```
        checkpoints::create_checkpoint(&table).await?;
```

I get the error

```
Error: Failed to convert into Arrow schema: Json error: Binary is not supported by JSON

Caused by:
    Json error: Binary is not supported by JSON
```

**What you expected to happen**:

The checkpoint file should be written

**How to reproduce it**:

Write a table with binary columns and try to write a checkpoint

**More details**:

Here's the relevant logs from before the error:

```
[2023-06-26T14:00:57Z DEBUG deltalake::checkpoints] Writing parquet bytes to checkpoint buffer.
[2023-06-26T14:00:57Z DEBUG deltalake::checkpoints] Writing to checkpoint parquet buffer...
```

### PR DESCRIPTION
**Pull request by ChewingGlass**
# Description
Avoid writing statistics for binary columns to fix JSON error thrown by Arrow

# Related Issue(s)
 - closes #1493

### CODE REVIEW

**Review by wjones127 — COMMENTED** [review]
This file is a bit messy, but your changes make sense. :/

I *think* you could accomplish the same thing in a more targeted way by removing and binary columns using `collect_stats_conversion` and `apply_stats_conversion`. Use `collect_stats_conversion` to get which columns are binary, and then apply to remove them from the value (can use `serde_json::Value::remove()`). LMK if that works instead.

**Comment by ChewingGlass** [comment]
Unfortunately you can't do this with stats conversion, the error occurs when making the ReaderBuilder, not when applying the values.

File: rust/src/writer/stats.rs [hunk 1]
```diff
@@ -238,8 +239,16 @@ impl StatsScalar {
...
-                Ok(Self::Decimal(val))
+
+                let str_val = val.to_string();
+                let decimal_string = if str_val.len() > *scale as usize {
+                    let (integer_part, fractional_part) =
+                        str_val.split_at(str_val.len() - *scale as usize);
+                    format!("{}.{}", integer_part, fractional_part)
+                } else {
+                    format!("0.{}", str_val)
+                };
```
Comment (wjones127) [inline rust/src/writer/stats.rs:250]: I think we also want to have negative scales. Also, could we unit test this directly in this file?

Comment (ChewingGlass) [reply rust/src/writer/stats.rs]: Added support for negative scales. Not going to be able to add tests for a bit. I added you to my fork so you can commit if you want to take a crack at it.

**Comment by wjones127** [comment]
We have a new failure for decimal, but I'm a little stumped on it for now.

**Comment by wjones127** [comment]
I think for decimal, we might be able to start using the `arbitrary_precision` feature of `serde_json`. Not sure how nicely it plays with decimals yet, but it seems to be the suggested route.

File: rust/src/action/checkpoints.rs [hunk 2]
```diff
@@ -281,6 +281,33 @@ pub async fn cleanup_expired_logs_for(
     }
 }
 
+// Filter binary from the schema so that it isn't serialized into JSON,
+// as arrow currently does not support this.
```
Comment (rtyler) [inline rust/src/action/checkpoints.rs:285]:
```suggestion
/// Filter binary from the schema so that it isn't serialized into JSON,
/// as arrow currently does not support this.
```

**Review by rtyler — COMMENTED** [review]
Looks promising to me, I'm looking forward to this being merged

**Comment by roeap** [comment]
@rtyler - i fear it may have been a bit too early to merge this., since the rust test are failing for this. since 0.13 was just released, we should look into releasing a fix asap. bot sure if @wjones127 already knows whats going on? Otherwise I might look into it once available again.

**Comment by rtyler** [comment]
@roeap Yes, I'm looking at this now. I must have been moving too quickly through some PRs. I now see that the test was failing but I'm not sure why I merged this :facepalm:  I must have mistaken this pull request for another one which I had open at the time.

I am going to land a revert into `main` directly, and cut a 0.13.1 with that revert just to avoid causing anybody problems
