### PR TITLE
fix: Address clippy lint warnings.

### LINKED ISSUE #741: Lint Errors with latest Rust tools
# Environment

**Delta-rs version**:
main

**Binding**: 
python -> make rust_check

**Environment**:
- **Cloud provider**: Vmware VM
- **OS**: ubuntu 20.04
- **Other**: Docker build using `curl https://sh.rustup.rs -sSf` to install rust. I end up with rust 1.63.0 which was release 2022-08-11

***
# Bug

**What happened**: The `make check-rust` target in the python directory failed with lint errors

**What you expected to happen**: I expect the build to pass on the main branch

**How to reproduce it**: Run `make check-rust` from any python environment. It appears to be related to a new release of the rust toolchain.

**More details**:

### PR DESCRIPTION
**Pull request by tsh56**
# Description
This addresses clippy lint warnings that appeared with the 1.63.0 release of rust. Most of the changes are reasonable and straight forward. I'm unsure about the best way to resolve python/src/lib.rs. I whitelisted the check, as py03 wants pymethods to have parameters with known sizes as compile time.

# Related Issue(s)
- closes #741 

# Documentation
https://rust-lang.github.io/rust-clippy/master/index.html#needless_return
https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
https://rust-lang.github.io/rust-clippy/master/index.html#borrow_deref_ref

### CODE REVIEW

File: rust/src/vacuum.rs [hunk 1]
```diff
@@ -236,7 +236,8 @@ impl Vacuum {
             });
         }
 
-        return plan.execute(table).await;
+        //return plan.execute(table).await;
```
Comment (houqp) [inline rust/src/vacuum.rs:239]: looks like this should be deleted

File: python/src/lib.rs [hunk 2]
```diff
@@ -1,4 +1,5 @@
 #![deny(warnings)]
+#![allow(clippy::borrow_deref_ref)]
```
Comment (houqp) [inline python/src/lib.rs:2]: curious which line is violating this error? we should probably fix that instead.

Comment (tsh56) [reply python/src/lib.rs:2]: The issue is directly related to pyo3.  There's already a [ticket](https://github.com/PyO3/pyo3/issues/2555) filed, and it appears to be fixed in main. Once the fixed is release this clippy exception shouldn't be necessary.

Comment (fvaleye) [reply python/src/lib.rs:2]: As a follow-up before merging, could you please add an issue to delete this clippy exception later?

**Comment by fvaleye** [comment]
Let me do it for you!

File: python/src/lib.rs (hunk 2 above)
Comment (houqp) [reply python/src/lib.rs:2]: Second to what @fvaleye said, would be good to add a follow up issue on github. Also a good practice to add comment in the code for temp workarounds that we plan to remove in the future.
