### PR TITLE
fix truncating signature on SAS

### LINKED ISSUE #1003: Azure SAS signatures ending in "=" don't work
# Environment

**Delta-rs version**: 0.6.4

**Binding**: Python

**Environment**:
- **Cloud provider**: Azure
- **OS**: MacOs
- **Other**:

***
# Bug

**What happened**: SAS tokens with signatures ending in "=" passed via storage_options get truncated and won't work.

**What you expected to happen**: SAS token authenticates all requests to Azure

**How to reproduce it**:
```
DeltaTable(
    "abfs://<container_name>",
    storage_options={
        "AZURE_STORAGE_ACCOUNT_NAME": "<account_name>",
        "sas_key": '?sv=2019-07-07&sr=c&sig=ain2DZplwGRn0RHuxrhJSwXl2bkCe0gyVMMJKTMAtFk=&st=2022-12-01T00:00:00Z&se=2022-12-02T00:00:00Z&sp=rl',
    },
)
```
Results in
```
PyDeltaTableError: Failed to load checkpoint: Failed to read checkpoint content: Generic MicrosoftAzure error: Error performing get request _delta_log/_last_checkpoint: response error "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
Time:2022-12-08T14:26:32.3390349Z</Message><AuthenticationErrorDetail>Signature fields not well formed.</AuthenticationErrorDetail></Error>", after 0 retries: HTTP status client error (403 Forbidden) for url (https://<account_name>.blob.core.windows.net/<container_name>/_delta_log/_last_checkpoint?sv=2019-07-07&sr=c&sig=ain2DZplwGRn0RHuxrhJSwXl2bkCe0gyVMMJKTMAtFk&st=2022-12-01T00:00:00Z&se=2022-12-02T00:00:00Z&sp=rl)
```

Note that the signature got truncated:
original sig: `sig=ain2DZplwGRn0RHuxrhJSwXl2bkCe0gyVMMJKTMAtFk=`
request url: `sig=ain2DZplwGRn0RHuxrhJSwXl2bkCe0gyVMMJKTMAtFk`

**More details**:
This might originate from the split function here: https://github.com/delta-io/delta-rs/blob/16bf4ccce0a3b965d3057ec20a38cd91d8f4fbc7/rust/src/builder/azure.rs#L222

### PR DESCRIPTION
**Pull request by damiondoesthings**
# Description
This fixes the truncation of Azure SAS signatures ending in "=", i.e. when using non-url-encoded SAS tokens.

# Related Issue(s)

closes #1003

### CODE REVIEW

File: rust/src/builder/azure.rs [hunk 1]
```diff
@@ -226,16 +226,10 @@ fn split_sas(sas: &str) -> Result<Vec<(String, String)>, BuilderError> {
...
     for kv_pair_str in kv_str_pairs {
-        let mut kv = kv_pair_str.trim().split('=');
-        let k = match kv.next().filter(|k| !k.chars().all(char::is_whitespace)) {
-            None => {
-                return Err(BuilderError::MissingCredential);
-            }
-            Some(k) => k,
-        };
-        let v = match kv.next().filter(|k| !k.chars().all(char::is_whitespace)) {
+        let kv = kv_pair_str.trim().split_once('=');
```
Comment (houqp) [inline rust/src/builder/azure.rs:229]: This can be simplified to:

```suggestion
        let (k, v) = kv_pair_str.trim().split_once('=').ok_or(BuilderError::MissingCredential);
```

**Review by houqp — APPROVED** [review]

**Review by roeap — APPROVED** [review]
Thanks for fixing this @damiondoesthings  - LGTM!
