### PR TITLE
fix: restore incremental update to reuse existing table state

### LINKED ISSUE #4276: [Bug]: update_incremental is not incremental
### What happened?

Starting from `update_incremental` here: https://github.com/delta-io/delta-rs/blob/001db7d7646a2100a27fb3ab0e1e4cd4f52fb4e9/crates/core/src/table/mod.rs#L206

The call chain ends up in `KernelSnapshot::builder_for`, which does not trigger the incremental `try_new_from_impl` path in Delta Kernel, causing the whole log to be replayed https://github.com/delta-io/delta-rs/blob/001db7d7646a2100a27fb3ab0e1e4cd4f52fb4e9/crates/core/src/kernel/snapshot/mod.rs#L83

Some relevant discussion on Slack

### Expected behavior

Incremental update

### Operating System

None

### Binding

None

### Bindings Version

_No response_

### Steps to reproduce

_No response_

### Relevant logs

```shell

```

### PR DESCRIPTION
**Pull request by ethan-tyler**
# Description
Fixes #4276

Incremental update from a cached table state could fall off the reuse path and reread older log state from scratch.

The fix here is to route `DeltaTable::update_incremental` back through `DeltaTableState::update` and add a narrow same version checkpoint refresh when `_last_checkpoint` points at the current version but the state isn't checkpoint backed.

Since there is multiple things going on in this area, I intentionally scoped to the regression only. 

This PR does not touch:
- https://github.com/delta-io/delta-kernel-rs/issues/2103
- #4269

Tests cover the original reread bug and checkpoint refresh behavior

# Related Issue(s)
- #4276

# Documentation

### CODE REVIEW

File: crates/core/src/table/mod.rs [hunk 1]
```diff
@@ -197,14 +197,29 @@ impl DeltaTable {
...
+        let Some(current_version) = self.state.as_ref().map(|state| state.version()) else {
+            self.state = Some(
+                DeltaTableState::try_new(&self.log_store, self.config.clone(), max_version).await?,
+            );
+            return Ok(());
+        };
+
+        if max_version.is_some_and(|version| version < current_version) {
+            self.state = Some(
+                DeltaTableState::try_new(&self.log_store, self.config.clone(), max_version).await?,
```
Comment (ion-elgreco) [inline crates/core/src/table/mod.rs]: I think we should raise here, update incremental should now allow you to downgrade, because then it's not update anymore haha

File: crates/core/src/table/state.rs [hunk 2]
```diff
@@ -161,12 +162,49 @@ impl DeltaTableState {
...
+                    log_store,
+                    refreshed_version,
+                    loaded_checkpoint_version,
+                )
+                .await?
+        {
+            tracing::trace!(
+                version = refreshed_version,
+                loaded_checkpoint_version = ?loaded_checkpoint_version,
+                "reloading table state to pick up a newer checkpoint at the current version"
```
Comment (ion-elgreco) [inline crates/core/src/table/state.rs:184]: Why are we reloading the state again if the state wasnt loaded from a checkpoint? This seems strange

File: crates/core/src/table/mod.rs (hunk 1 above)
Comment (ethan-tyler) [reply crates/core/src/table/mod.rs]: Fair question and I see your concern. This was the existing explicit version behavior and for this PR I was focused on restoring incremental forward updates. 

`read_delta_log_test` exercises `update_incremental(Some(...))` and `load_version() `delegates through it.

As a long term design, I agree `update_incremental` should be strictly forward only, however I think that's a separate cleanup where `load_version()` owns the downgrade path and we update tests/callers together. lmk what you think

File: crates/core/src/table/state.rs (hunk 2 above)
Comment (ethan-tyler) [reply crates/core/src/table/state.rs:184]: This is a narrow workaround for a current same version refresh bug/gap in the snapshot update stack.

If state is already at version N but was loaded without a checkpoint, and a checkpoint for N gets written later, a normal same version update will not adopt it because `Snapshot::update()` and `EagerSnapshot::update()` both return early when `target == current`.

The `_last_checkpoint` check is there to cover that specific case until the underlying same version refresh behavior is fixed lower in the stack. It’s not intended as general checkpoint selection logic in delta-rs.

File: crates/core/src/table/mod.rs (hunk 1 above)
Comment (ion-elgreco) [reply crates/core/src/table/mod.rs]: But if you are focusing on restoring incremental forward updates, then for that reason we should not allow this code path

File: crates/core/src/table/state.rs (hunk 2 above)
Comment (ion-elgreco) [reply crates/core/src/table/state.rs:184]: But is this a bug upstream in kernel or in our snapshot updating logic?

File: crates/core/src/table/mod.rs (hunk 1 above)
Comment (ethan-tyler) [reply crates/core/src/table/mod.rs]: That’s reasonable. I just was trying to avoid changing explicit version behavior in the same regression fix, but agree and will make the change.

File: crates/core/src/table/state.rs (hunk 2 above)
Comment (ethan-tyler) [reply crates/core/src/table/state.rs:184]: I think the gap is in our snapshot update stack and not a kernel issue. `Snapshot::update()` and `EagerSnapshot::update()` both no-op when `target == current` which causes us to never adopt a checkpoint written later for the current version.

We should fix the underlying same version update behavior, but that changes update semantics in the snapshot layer and IMO should be a separate follow up. I opened #4280 to track it.  This PR should be a narrow workaround keeps the scope on the regression. Wdyt?

Comment (ion-elgreco) [reply crates/core/src/table/state.rs:184]: I don't understand tbh why we should care if a checkpoint is written at version the state already is in? We already read all logs and reconciled them, we can just keep reading from that point onwards?

Comment (ethan-tyler) [reply crates/core/src/table/state.rs:184]: We care because the base changed and  not that version N's contents changed. State was built from replay, but now there's a checkpoint for N. We want to rebase onto that so future updates start from a checkpoint backed base instead of replayed state. Without it, same version update is always a no-op and we never adopt the checkpoint.

Comment (ethan-tyler) [reply crates/core/src/table/state.rs:184]: Here's an example:

Long lived reader loads table at version N from replay (no checkpoint exists yet). Later, a checkpoint for N gets written and old log files get cleaned up. Same version update is a no-op today, and the loaded state never rebases onto the checkpoint.

Now when the reader tries to advance to N+1, it's working from a replay base whose underlying log files may have been cleaned up. 

You can see this in the checkpoint_writer regression test

Comment (ion-elgreco) [reply crates/core/src/table/state.rs:184]: Okay thanks for the example!

File: crates/core/src/table/mod.rs (hunk 1 above)
Comment (ion-elgreco) [reply crates/core/src/table/mod.rs]: Great, if you make the change we can merge it!
