### PR TITLE
fix(rust): handle 429 from GCS

### LINKED ISSUE #2451: Handle rate limiting during write contention
During concurrent writes there is going to be contention for the next commit `.json` file.
GCS has a hard limit on 1 mutation operation per second per key, so that gets hit immediately.
You get back a 429, which should just be interpreted as "someone else wrote that key already, advance to the next commit id and try again" but is instead being surfaced as an error:

```
Error: Generic DeltaTable error: Version mismatch
Error: Generic GCS error: Client error with status 429 Too Many Requests: <?xml version='1.0' encoding='UTF-8'?><Error><Code>SlowDown</Code><Message>The object exceeded the rate limit for object mutation operations (create, update, and delete). Please reduce your request rate. See https://cloud.google.com/storage/docs/gcs429.</Message><Details>The object bucket-00d0331/test/delta/_delta_log/00000000000000000021.json exceeded the rate limit for object mutation operations (create, update, and delete). Please reduce your request rate. See https://cloud.google.com/storage/docs/gcs429.</Details></Error>
Error: Generic DeltaTable error: Version mismatch
Error: Generic GCS error: Client error with status 429 Too Many Requests: <?xml version='1.0' encoding='UTF-8'?><Error><Code>SlowDown</Code><Message>The object exceeded the rate limit for object mutation operations (create, update, and delete). Please reduce your request rate. See https://cloud.google.com/storage/docs/gcs429.</Message><Details>The object bucket-00d0331/test/delta/_delta_log/00000000000000000019.json exceeded the rate limit for object mutation operations (create, update, and delete). Please reduce your request rate. See https://cloud.google.com/storage/docs/gcs429.</Details></Error>
Error: Generic GCS error: Client error with status 429 Too Many Requests: <?xml version='1.0' encoding='UTF-8'?><Error><Code>SlowDown</Code><Message>The object exceeded the rate limit for object mutation operations (create, update, and delete). Please reduce your request rate. See https://cloud.google.com/storage/docs/gcs429.</Message><Details>The object bucket-00d0331/test/delta/_delta_log/00000000000000000019.json exceeded the rate limit for object mutation operations (create, update, and delete). Please reduce your request rate. See https://cloud.google.com/storage/docs/gcs429.</Details></Error>
```

Test code:

```python
import os

os.environ['RUST_LOG'] = 'INFO'

from time import time
from concurrent.futures import ProcessPoolExecutor

import polars as pl
from deltalake import DeltaTable, write_deltalake
from google.cloud import storage



def worker(uri: str, df: pl.DataFrame) -> None:
    table = DeltaTable(uri, log_buffer_size=1024 * 1024)
    table.update_incremental()

    print('writing in a loop')
    while True:
        try:
            start = time()
            write_deltalake(table, df.to_arrow(), engine='rust', mode='append')
            print('Time taken:', time() - start)
        except Exception as e:
            print('Error:', e)
            continue


if __name__ == '__main__':
    print('Deleting all files in the bucket')
    client = storage.Client()
    bucket = client.get_bucket('bucket-00d0331')
    for blob in bucket.list_blobs(prefix='test/delta'):
        blob.delete()
    
    df = pl.DataFrame({
        'a': [1, 2, 3],
        'b': [4, 5, 6],
    })


    uri = 'gs://bucket-00d0331/test/delta'

    print('initializing delta table')
    write_deltalake(uri, df.to_arrow(), engine='rust', mode='append')

    with ProcessPoolExecutor(32) as executor:
        futures = [
            executor.submit(worker, uri, df)
            for _ in range(32)
        ]
        for future in futures:
            future.result()
```

### PR DESCRIPTION
**Pull request by adriangb**
Fixes #2451 

This is probably not the best implementation but it at least let me test the outcome.

Here's my test script:

```python
import os
from uuid import uuid4

os.environ['RUST_LOG'] = 'INFO'

from time import time
from concurrent.futures import ProcessPoolExecutor

import polars as pl
from deltalake import DeltaTable, write_deltalake

def worker(uri: str, df: pl.DataFrame) -> None:
    table = DeltaTable(uri, log_buffer_size=1024 * 1024)
    table.update_incremental()

    print('writing in a loop')
    while True:
        try:
            start = time()
            write_deltalake(table, df.to_arrow(), engine='rust', mode='append')
            print('Time taken:', time() - start)
        except Exception as e:
            print('Python error:', e)
            continue

if __name__ == '__main__':    
    df = pl.DataFrame({
        'a': [1, 2, 3],
        'b': [4, 5, 6],
    })

    uri = f'gs://bucket-00d0331/test/delta/{uuid4()}'

    print('initializing delta table')
    write_deltalake(uri, df.to_arrow(), engine='rust', mode='append')

    with ProcessPoolExecutor(32) as executor:
        futures = [
            executor.submit(worker, uri, df)
            for _ in range(32)
        ]
        for future in futures:
            future.result()
```

With this change I now get:

```
Attempt 1 failed: Version 1 already exists
Attempt 1 failed: Version 1 already exists
Python error: Generic DeltaTable error: Version mismatch
Time taken: 1.4619898796081543
Attempt 1 failed: Version 1 already exists
Attempt 2 failed: Version 2 already exists
Attempt 1 failed: Version 1 already exists
Attempt 2 failed: Version 2 already exists
Python error: Generic DeltaTable error: Version mismatch
Attempt 1 failed: Version 1 already exists
Attempt 1 failed: Version 1 already exists
Attempt 1 failed: Version 1 already exists
Attempt 1 failed: Version 1 already exists
Attempt 1 failed: Version 1 already exists
Attempt 2 failed: Version 2 already exists
Attempt 1 failed: Version 1 already exists
Attempt 1 failed: Version 1 already exists
Attempt 1 failed: Version 1 already exists
Attempt 1 failed: Version 1 already exists
Attempt 1 failed: Version 1 already exists
Attempt 1 failed: Version 1 already exists
Attempt 1 failed: Version 1 already exists
Attempt 1 failed: Version 1 already exists
Attempt 3 failed: Version 3 already exists
Attempt 1 failed: Version 1 already exists
Attempt 1 failed: Version 1 already exists
Attempt 3 failed: Version 3 already exists
Attempt 1 failed: Version 2 already exists
Attempt 2 failed: Version 2 already exists
Attempt 2 failed: Version 2 already exists
Attempt 1 failed: Version 1 already exists
Attempt 2 failed: Version 2 already exists
Attempt 1 failed: Version 2 already exists
Attempt 2 failed: Version 2 already exists
Attempt 2 failed: Version 2 already exists
Attempt 2 failed: Version 2 already exists
Attempt 1 failed: Version 1 already exists
Attempt 1 failed: Version 1 already exists
Attempt 2 failed: Version 2 already exists
Attempt 2 failed: Version 2 already exists
Attempt 1 failed: Version 2 already exists
Attempt 2 failed: Version 2 already exists
Attempt 1 failed: Version 2 already exists
Attempt 2 failed: Version 2 already exists
Attempt 1 failed: Version 1 already exists
Python error: Generic DeltaTable error: Version mismatch
Attempt 2 failed: Version 2 already exists
Attempt 2 failed: Version 2 already exists
Attempt 1 failed: Version 2 already exists
Attempt 3 failed: Version 3 already exists
Attempt 1 failed: Version 2 already exists
Attempt 1 failed: Version 2 already exists
Attempt 2 failed: Version 2 already exists
Attempt 2 failed: Version 2 already exists
Attempt 2 failed: Version 2 already exists
Attempt 2 failed: Version 2 already exists
Attempt 3 failed: Version 3 already exists
Attempt 4 failed: Version 4 already exists
Attempt 3 failed: Version 3 already exists
Attempt 3 failed: Version 3 already exists
Attempt 2 failed: Version 3 already exists
Attempt 3 failed: Version 3 already exists
Attempt 3 failed: Version 3 already exists
Attempt 2 failed: Version 3 already exists
Attempt 3 failed: Version 3 already exists
Attempt 2 failed: Version 3 already exists
Attempt 2 failed: Version 2 already exists
Attempt 2 failed: Version 2 already exists
Attempt 1 failed: Version 2 already exists
Attempt 3 failed: Version 3 already exists
Attempt 3 failed: Version 3 already exists
Attempt 3 failed: Version 3 already exists
Attempt 2 failed: Version 3 already exists
Attempt 2 failed: Version 2 already exists
Attempt 3 failed: Version 3 already exists
Python error: Generic DeltaTable error: Version mismatch
```

So this is an improvement but the behavior is still problematic: I'm not sure that it's updating to try the next version every time a commit fails. I also don't know if updating to the next version is even the right thing to do, maybe it should be refreshing the table state before retrying in case it's gotten far out of sync (e.g. because writing the data took a long time). Buy maybe these are crate wide or protocol wide issues not related to the particularities of GCS.

### CODE REVIEW

**Comment by adriangb** [comment]
cc @ion-elgreco

File: crates/gcp/src/storage.rs [hunk 1]
```diff
@@ -0,0 +1,137 @@
+//! AWS S3 storage backend.
```
Comment (ion-elgreco) [inline crates/gcp/src/storage.rs:1]: Still references S3 : )

Comment (adriangb) [reply crates/gcp/src/storage.rs:1]:
```suggestion
//! GCP GCS storage backend.
```

**Review by ion-elgreco — DISMISSED** [review]

**Review by rtyler — APPROVED** [review]

**Review by ion-elgreco — APPROVED** [review]
