### PR TITLE
fix: add conversion for string for `Field::TimestampMicros` (#1372)

### LINKED ISSUE #1372: Unable to read timestamp fields from column statistics
# Environment

**Delta-rs version**: 0.10.0

**Binding**: rust

**Environment**:
N/A

***
# Bug

**What happened**:

With a field defined as 
```rs
SchemaField::new(
  "EdgeEndTimestamp".to_string(),
  SchemaDataType::primitive("timestamp".to_string()),
  true,
  HashMap::new(),
),
```
 
I get the following error when querying using datafusion.

```json
{
  "timestamp": "2023-05-16T18:58:40.206275Z",
  "level": "WARN",
  "fields": {
    "message": "Unexpected type when parsing min/max values for EdgeEndTimestamp. Found 2023-05-16 18:56:10 +00:00",
    "log.target": "deltalake::action::parquet_read",
    "log.module_path": "deltalake::action::parquet_read",
    "log.file": "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/deltalake-0.10.0/src/action/parquet_read/mod.rs",
    "log.line": 216
  },
  "target": "deltalake::action::parquet_read"
}
```

**What you expected to happen**:

Query to succeed, statistics read correctly.

**How to reproduce it**:

1. define a timestamp field
2. write data
3. query back data

**More details**:

It looks like the format might have changed for timestamp fields? It no longer looks like RFC3339. I have some data written using this (maybe incorrect) format. Would be great if the fix also supports this format too

### PR DESCRIPTION
**Pull request by cmackenzie1**
# Description

Add a match statement to handle the case when timestamp is encoded as `TimestampMicros` in the parquet file.

# Related Issue(s)

- resolves #1372.

# Documentation
N/A

### CODE REVIEW

File: rust/src/action/parquet_read/mod.rs [hunk 1]
```diff
@@ -269,13 +272,27 @@ fn primitive_parquet_field_to_json_value(field: &Field) -> Result<serde_json::Va
...
 
+fn convert_timestamp_micros_to_string(value: i64) -> Result<String, &'static str> {
+    let seconds = value / 1_000_000;
+    let microseconds = (value % 1_000_000) as u32;
+
+    let dt: chrono::DateTime<Utc> = Utc
+        .timestamp_opt(seconds, microseconds * 1_000)
+        .single()
+        .ok_or("Value out of bounds")?;
+    Ok(dt.to_rfc3339_opts(SecondsFormat::Micros, true))
```
Comment (cmackenzie1) [inline rust/src/action/parquet_read/mod.rs:293]: Do we want `SecondsFormat::Micros` here or match with Millisecond format as above?

Comment (wjones127) [reply rust/src/action/parquet_read/mod.rs:293]: Seems like micros is fine. Spec specifically allows that one. https://github.com/delta-io/delta/blob/master/PROTOCOL.md#partition-value-serialization

**Review by wjones127 — APPROVED** [review]

**Review by roeap — APPROVED** [review]
