### PR TITLE
bugfix: Make sure vacuum works on relative paths

### LINKED ISSUE #663: vacuum isn't actually deleting files
# Environment

**Delta-rs version**: 0.5.8

**Binding**: Python

**Environment**: localhost

***
# Bug

**What happened**: Ran `dt.vacuum(retention_hours=0, enforce_retention_duration=False, dry_run=False)` and files didn't actually get deleted.

**What you expected to happen**: I thought the stale files would actually get deleted.

**How to reproduce it**: Here's [the notebook to reproduce this](https://github.com/MrPowers/delta-examples/blob/master/notebooks/delta-rs/intro-to-delta-rs.ipynb).

**More details**: `enforce_retention_duration` was added recently and that's successfully letting me bypass the retention duration error I was facing before.  Let me know if I'm missing something here and there's a way to get the files vacuumed with the existing code.

### PR DESCRIPTION
**Pull request by wjones127**
# Description

It seems that when we pass a relative path to `DeltaTable()`, vacuum doesn't actually delete files. I've added tests in Python which is more convenient now that we have a writer.

# Related Issue(s)

* Fixes #663

# Documentation

### CODE REVIEW

File: rust/src/delta.rs [hunk 1]
```diff
@@ -1277,12 +1277,7 @@ impl DeltaTable {
         if dry_run {
             return Ok(files_to_delete);
         }
-
-        let paths = &files_to_delete
-            .iter()
-            .map(|rel_path| self.storage.join_path(&self.table_uri, rel_path))
-            .collect::<Vec<_>>();
-        match self.storage.delete_objs(paths).await {
+        match self.storage.delete_objs(&files_to_delete).await {
```
Comment (wjones127) [inline rust/src/delta.rs:1280]: I'm not sure how this was working in object stores, but in local fs `files_to_delete` was already absolute. Local file system used `Path::join()`, which had the fortunate behavior of just using the second path if it was already absolute.

Comment (roeap) [reply rust/src/delta.rs:1280]: well... maybe its not :) - will have a closer look once i get to #647.

**Review by roeap — APPROVED** [review]
LGTM
