### PR TITLE
Fix names and nullability when creating RecordBatch from MapArray

### LINKED ISSUE #1257: Not matching column names when creating a RecordBatch from MapArray
# Environment

**Delta-rs version**: 0.8.0

**Binding**: Rust

**Environment**:
- **Cloud provider**: N/A
- **OS**: Linux
- **Other**: RustExplorer ( https://www.rustexplorer.com/b/o7bfm4 )

***
# Bug

**What happened**: When trying to create a RecordBatch with MapArray, I get the following error:
```
thread 'main' panicked at 'Failed to create RecordBatch: InvalidArgumentError("column types must match schema types, expected Map(Field { name: \"key_value\", data_type: Struct([Field { name: \"key\", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"value\", data_type: Binary, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, false) but found Map(Field { name: \"entries\", data_type: Struct([Field { name: \"keys\", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"values\", data_type: Binary, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, false) at column index 0")', src/main.rs:66:90
```

**What you expected to happen**: Successful creation of `RecordBatch` without any errors.

**How to reproduce it**: Create a `MapArray` and `RecordBatch` with it (See rust explorer link above).

**More details**:
I believe these lines are at fault. https://github.com/delta-io/delta-rs/blob/main/rust/src/delta_arrow.rs#L145-L161
Hopefully I will be able to test this hypothesis and make a PR in few hours.

### PR DESCRIPTION
**Pull request by balbok0**
# Description
When creating a RecordBatch with one of the columns being a MapArray, there are issues with naming of sub-columns, as well as nullability of the "elements/key_value" sub-column.

# Related Issue(s)

- closes #1257

# Documentation

See https://www.rustexplorer.com/b/o7bfm4 for a breaking example.
I initially thought that the issue is specifically for array with 0-length maps, but `nullable` mismatch happens even when all of the map elements have values.

### CODE REVIEW

**Comment by rtyler** [comment]
Thanks for the pull request! @balbok0 would you be able to take your failing example and turn that into a unit or integration test so we don't have this regression in the future?

**Comment by wjones127** [comment]
I’d like for us to fix this, but I also hope we can find a way to simultaneously support older PyArrow versions in the Python bindings.

**Comment by balbok0** [comment]
@wjones127 are there some specific pyarrow versions you have in mind? I wasn't able to find a specific arrow-cpp/pyarrow version that changed the naming scheme.

**Comment by balbok0** [comment]
Added failing example as a test.

File: rust/src/delta_arrow.rs [hunk 1]
```diff
@@ -751,6 +752,71 @@ mod tests {
...
+                ArrowDataType::Struct(vec![
+                    ArrowField::new("key", ArrowDataType::Int8, false),
+                    ArrowField::new("value", ArrowDataType::Binary, true),
+                ]),
+                true,
+            )),
+            false,
+        );
+        assert_eq!(
+            <crate::SchemaDataType as TryFrom<&ArrowDataType>>::try_from(&timestamp_field).unwrap(),
```
Comment (wjones127) [inline rust/src/delta_arrow.rs:769]:
```suggestion
        );
        let converted_map: crate::SchemaDataType = (&timestamp_field).try_into().unwrap();
        assert_eq!(
            converted_map,
```

**Review by wjones127 — CHANGES_REQUESTED** [review]
This generally looks good. I was worried about PyArrow and other languages because the Arrow standard specifies field names as "key" not "keys" and "value" not "values" (arrow-rs deviates from this). But the PyArrow C Data Interface import actually ignores these field names on map types anyways, so it shouldn't matter that they are different. So we can ignore that worry.

I have a few small nits on the tests, but otherwise looks good to go.

**Comment by wjones127** [comment]
Oh and could you rebase? We just fixed some of the deprecation warnings.

**Comment by balbok0** [comment]
Thanks for comments! I applied changes and rebased. Lmk if there is anything else that needs to done before merge.

**Review by wjones127 — APPROVED** [review]
