### PR TITLE
Parse partition values before handing to PyArrow

### LINKED ISSUE #563: Cannot read delta table partitioned by a date typed column
# Environment

**Delta-rs version**: 0.5.6

**Binding**: python

**Environment**: any
- **Cloud provider**: any
- **OS**: any
- **Other**: n/a

***
# Bug

**What happened**: Cannot read delta table partitioned by a date type column.

**What you expected to happen**: It should be able to read tables partitioned by date.

**How to reproduce it**:

Generate fake data and save it
```python
from pyspark.sql import functions as F

df = spark.range(5).withColumn("date", F.lit("2021-01-01").cast("date"))
df.write.partitionBy("date").format("delta").save("partitioned_df")
print(df.schema())
# StructType(List(StructField(id,LongType,false),StructField(date,DateType,true)))
```

Read this with deltalake
```python
from deltalake import DeltaTable

DeltaTable("partitioned_df").to_pandas()
```

This raises `ArrowNotImplementedError: Unsupported cast from string to date32 using function cast_date32`

Full trace:

```
ArrowNotImplementedError                  Traceback (most recent call last)
/Users/buraky/delta/sketch.ipynb Cell 29' in <module>
----> 1 DeltaTable("partitioned_df").to_pandas()

File ~/Environments/delta/lib/python3.8/site-packages/deltalake/table.py:321, in DeltaTable.to_pandas(self, partitions, columns, filesystem)
    307 def to_pandas(
    308     self,
    309     partitions: Optional[List[Tuple[str, str, Any]]] = None,
    310     columns: Optional[List[str]] = None,
    311     filesystem: Optional[Union[str, pa_fs.FileSystem]] = None,
    312 ) -> "pandas.DataFrame":
    313     """
    314     Build a pandas dataframe using data from the DeltaTable.
    315 
   (...)
    319     :return: a pandas dataframe
    320     """
--> 321     return self.to_pyarrow_table(
    322         partitions=partitions, columns=columns, filesystem=filesystem
    323     ).to_pandas()

File ~/Environments/delta/lib/python3.8/site-packages/deltalake/table.py:303, in DeltaTable.to_pyarrow_table(self, partitions, columns, filesystem)
    289 def to_pyarrow_table(
    290     self,
    291     partitions: Optional[List[Tuple[str, str, Any]]] = None,
    292     columns: Optional[List[str]] = None,
    293     filesystem: Optional[Union[str, pa_fs.FileSystem]] = None,
    294 ) -> pyarrow.Table:
    295     """
    296     Build a PyArrow Table using data from the DeltaTable.
    297 
   (...)
    301     :return: the PyArrow table
    302     """
--> 303     return self.to_pyarrow_dataset(
    304         partitions=partitions, filesystem=filesystem
    305     ).to_table(columns=columns)

File ~/Environments/delta/lib/python3.8/site-packages/pyarrow/_dataset.pyx:323, in pyarrow._dataset.Dataset.to_table()

File ~/Environments/delta/lib/python3.8/site-packages/pyarrow/_dataset.pyx:2311, in pyarrow._dataset.Scanner.to_table()

File ~/Environments/delta/lib/python3.8/site-packages/pyarrow/error.pxi:143, in pyarrow.lib.pyarrow_internal_check_status()

File ~/Environments/delta/lib/python3.8/site-packages/pyarrow/error.pxi:120, in pyarrow.lib.check_status()

ArrowNotImplementedError: Unsupported cast from string to date32 using function cast_date32
```

**More details**:

As the exception message says, it seems like there is no implementation for string to date32 in arrow. I checked arrow and saw that it eventually calls [this one](https://github.com/apache/arrow/blob/master/cpp/src/arrow/compute/kernels/scalar_cast_temporal.cc#L473) I guess, and string to date32 casting is not implemented.

**Question**: Is this a concern for deltalake project, or should this be handled within pyarrow?

### PR DESCRIPTION
**Pull request by wjones127**
# Description

We were providing all partition values as strings, by PyArrow expects them to be parsed to the correct type.

# Related Issue(s)

- closes #563

# Documentation

### CODE REVIEW

**Review by houqp — APPROVED** [review]

**Comment by houqp** [comment]
The build error is caused by rustc update and not related to this PR. @fvaleye you want to take a final look at this change?

**Review by fvaleye — APPROVED** [review]
LGTM! Thank you @wjones127

**Comment by wjones127** [comment]
Force pushed with no new changes to rerun CI.

File: python/src/lib.rs [hunk 1]
```diff
@@ -297,19 +298,32 @@ fn json_value_to_py(value: &serde_json::Value, py: Python) -> PyObject {
...
     for (column, value) in partitions_values.iter() {
         if let Some(value) = value {
+            // value is a string, but needs to be parsed into appropriate type
+            let column_type = schema
+                .field_with_name(column)
+                .map_err(|_| PyDeltaTableError::new_err("Partition column not found in schema"))?
+                .data_type()
+                .clone()
+                .into_py(py);
+            // pa.scalar(value).cast(type)
```
Comment (fvaleye) [inline python/src/lib.rs:319]: Is it a missing comment?

File: python/tests/data/gen_date_data.py [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+
+df = spark.range(5).repartition(1).withColumn("date", F.lit("2021-01-01").cast("date"))
+df.write.partitionBy("date").format("delta").save("date_partitioned_df")
+
+df = (
+    spark.range(5)
+    .repartition(1)
+    .withColumn("date", F.lit("2021-01-01").cast("timestamp"))
+)
+df.write.partitionBy("date").format("delta").save("timestamp_partitioned_df")
```
Comment (fvaleye) [inline python/tests/data/gen_date_data.py:26]: Do you think we need to keep this generation file? The generated dataset should be sufficient.

Comment (wjones127) [reply python/tests/data/gen_date_data.py:26]: I thought it might be helpful, but I can remove it. Once this is merged, I'll rebase #566 and rewrite the tests to use the pyarrow based writer to validate the round trip.

File: python/src/lib.rs (hunk 1 above)
Comment (wjones127) [reply python/src/lib.rs:319]: It's meant to annotate what the next line is doing in Python. I can add `Python for below: ` prefix to it for clarity.

Comment (wjones127) [reply python/src/lib.rs]: I ended up just deleting that comment.

File: python/tests/data/gen_date_data.py (hunk 2 above)
Comment (wjones127) [reply python/tests/data/gen_date_data.py]: Deleted.

**Review by fvaleye — APPROVED** [review]
LGTM thank you @wjones127 👍
